SELECT 
    t1.COUNTY_CODE,
    t1.COUNTY_NAME,
    t1.DISTRICT_CODE,
    t1.DISTRICT_NAME,
    t1.SCHOOL_CODE,
    t1.SCHOOL_NAME,
    t1.SCHOOL_GRADESPAN,
    t2.TESTPRG,
    t2.SUBJECT ACADEMIC_SUBJECT,
    t2.TPP,
    t2.TP,
    t2.TAP,
    t3.GRADE03,
    round(0.01*t2.TPP*t3.GRADE03) TPP_ACTUAL,
    round(0.01*t2.TP*t3.GRADE03) TP_ACTUAL,
    t3.GRADE03 - (round(0.01*t2.TPP*t3.GRADE03)+round(0.01*t2.TP*t3.GRADE03))  TAP_ACTUAL
FROM
    nj_edu.sch_header t1
        JOIN
    nj_edu.assessment t2 ON (t1.COUNTY_CODE = t2.COUNTY_CODE
        AND t1.DISTRICT_CODE = t2.DISTRICT_CODE
        AND t1.SCHOOL_CODE = t2.SCHOOL_CODE)
JOIN nj_edu.enrollment t3 on (t1.COUNTY_CODE = t3.COUNTY_CODE
        AND t1.DISTRICT_CODE = t3.DISTRICT_CODE
        AND t1.SCHOOL_CODE = t3.SCHOOL_CODE)        
WHERE
    t1.COUNTY_NAME = 'CHARTERS'
        AND t1.SCHOOL_GRADESPAN LIKE 'KG%'
        AND t2.TESTPRG = 'NJASK3'