CREATE TABLE ct_enrollment
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'PK' SCHOOL_GRADE,
PK CLASS_SIZE FROM enrollment T1
where PK is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'KG' SCHOOL_GRADE,
KG CLASS_SIZE FROM enrollment T1
where KG is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE01' SCHOOL_GRADE,
GRADE01 CLASS_SIZE FROM enrollment T1
where GRADE01 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE02' SCHOOL_GRADE,
GRADE02 CLASS_SIZE FROM enrollment T1
where GRADE02 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE03' SCHOOL_GRADE,
GRADE03 CLASS_SIZE FROM enrollment T1
where GRADE03 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE04' SCHOOL_GRADE,
GRADE04 CLASS_SIZE FROM enrollment T1
where GRADE04 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE05' SCHOOL_GRADE,
GRADE05 CLASS_SIZE FROM enrollment T1
where GRADE05 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE06' SCHOOL_GRADE,
GRADE06 CLASS_SIZE FROM enrollment T1
where GRADE06 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE07' SCHOOL_GRADE,
GRADE07 CLASS_SIZE FROM enrollment T1
where GRADE07 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE08' SCHOOL_GRADE,
GRADE08 CLASS_SIZE FROM enrollment T1
where GRADE08 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE09' SCHOOL_GRADE,
GRADE09 CLASS_SIZE FROM enrollment T1
where GRADE09 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE10' SCHOOL_GRADE,
GRADE10 CLASS_SIZE FROM enrollment T1
where GRADE10 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE11' SCHOOL_GRADE,
GRADE11 CLASS_SIZE FROM enrollment T1
where GRADE11 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'GRADE12' SCHOOL_GRADE,
GRADE12 CLASS_SIZE FROM enrollment T1
where GRADE12 is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'UG' SCHOOL_GRADE,
UG CLASS_SIZE FROM enrollment T1
where UG is not null
UNION all
SELECT COUNTY_CODE, DISTRICT_CODE, SCHOOL_CODE, 
'ROW_TOTAL' SCHOOL_GRADE,
ROW_TOTAL CLASS_SIZE FROM enrollment T1
where ROW_TOTAL is not null
